apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skymechanics-ingress
  namespace: skymechanics
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: skymechanics.local
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8200
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: jobs-service
                port:
                  number: 8202
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: aircraft-service
                port:
                  number: 8201
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
