apiVersion: v1
kind: ServiceAccount
metadata:
  name: skymechanics-sa
  namespace: skymechanics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skymechanics-role
  namespace: skymechanics
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skymechanics-rolebinding
  namespace: skymechanics
subjects:
  - kind: ServiceAccount
    name: skymechanics-sa
    namespace: skymechanics
roleRef:
  kind: Role
  name: skymechanics-role
  apiGroup: rbac.authorization.k8s.io
